apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opal-cicd

bases:
  - ../../argocd
  - ../../components/traefik
  - ../../components/secrets

patches:
  - argocd_select_path.yaml
  - traefik_patch.yaml