apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opal-cicd

bases:
  - ../components/secrets/
  - ../components/traefik/

resources:
  - opal_argo_cd.yaml
  - opal_argocd_application.yaml
  - namespace.yaml