apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opal-dev

resources:
  - ../../base/
  - ingress.yaml
  - init_singleuser_image.yaml

configMapGenerator:
  - name: deployment-env
    envs:
      - k8.env

secretGenerator:
  - name: tls-certs
    files:
      - tls.crt
      - tls.key
    type: "kubernetes.io/tls"
  - name: minio-certs
    files:
      - tls.crt
    type: Opaque

#patches:
#  - patch: |-
#      op: delete
#      apiVersion: apps/v1
#      kind: Deployment
#      metadata:
#        name: traefik
#        namspace: opal-dev
#        labels:
#          app:traefik
