apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - opal_metaflow_metadata.yaml
  - opal_argo_workflows.yaml
  - workflows_account.yaml
  
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ARGO_NAMESPACE
        value: opal
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: BASE_HREF
        value: /argo/
    - op: add
      path: "/spec/template/spec/containers/0/args/-"
      value:
        --secure=false
  target:
    kind: Deployment
    name: argo-server