apiVersion: v1
kind: Service
metadata:
  namespace: jupyterhub
  name: keycloak
  labels:
    component: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443 
    - name: other-http
      port: 8080
  selector:
    component: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jupyterhub
  name: keycloak
  labels:
    component: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      component: keycloak
  template:
    metadata:
      labels:
        component: keycloak
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: keycloak
          image: registry1.dso.mil/ironbank/opensource/keycloak/keycloak:19.0.3-legacy
          env:
            - name: KEYCLOAK_JUPYTERHUB_CLIENT_ID
              value: opal-jupyterhub
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_ADDR
              value: database
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_DATABASE
              value: keycloak
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: opal
            #- name: JAVA_TOOL_OPTIONS
            #  value: "-Dcom.redhat.fips=false"
          envFrom:
            - secretRef:
                name: token-env
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            exec:
              command:
                ["curl", "--fail", "http://localhost:9990/health"]
            initialDelaySeconds: 90
            timeoutSeconds: 2
            failureThreshold: 60
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                ["curl", "--fail", "http://localhost:9990/health"]
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-setup
  namespace: jupyterhub
  labels:
    component: keycloak
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: keycloak-setup
        image: registry1.dso.mil/ironbank/opensource/keycloak/keycloak:19.0.3-legacy
        command: ["sh", "/usr/local/bin/keycloak_script.sh"]
        volumeMounts:
          - name: setup-script
            mountPath: /usr/local/bin/keycloak_script.sh
            subPath: keycloak_script.sh
        env:
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: opal
          - name: MINIO_TEST_USER
            value: opaluser
          - name: MINIO_TEST_USER_PASSWORD
            value: opalpassword
        envFrom:
          - configMapRef:
              name: opal-env
          - secretRef:
              name: token-env
      restartPolicy: Never
      volumes:
        - name: setup-script
          configMap:
            name: keycloak-setup-script

