apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: jupyterhub
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: minio-k8s-prod.opalacceptance.dso.mil
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9002
    - host: traefik-k8s-prod.opalacceptance.dso.mil
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik
                port:
                  name: dashboard
    - host: kc-k8s-prod.opalacceptance.dso.mil
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
    - host: opal-k8s-prod.opalacceptance.dso.mil
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-public
                port:
                  number: 80
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: traefik-dashboard-ingress
#  namespace: jupyterhub
#  annotations:
#    traefik.ingress.kubernetes.io/router.entrypoints: traefik
#    #traefik.ingress.kubernetes.io/router.tls: "true"
#spec:
#  rules:
#    - host: traefik-k8s-prod.opalacceptance.dso.mil
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: traefik
#                port:
#                  name: dashboard
#                  #number: 8080
