apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opal

resources:
- kubernetes_files/catalog.yaml
- kubernetes_files/jupyterhub.yaml
- kubernetes_files/keycloak.yaml
- kubernetes_files/minio.yaml
- kubernetes_files/postgres.yaml

# disable suffixes on configmaps and secrets
# necessary for jupyterhub to find those things
# when it starts a new user server
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- envs:
  - extra_resources/.env
  name: opal-env
- files:
  - extra_resources/jupyterhub_config.py
  name: jupyterhub-config-py
- files:
  - extra_resources/startup_script.bash
  name: jupyterhub-startup-script
- files:
  - extra_resources/Dockerfile
  name: singleuser-torch-dockerfile
- files:
  - extra_resources/keycloak_script.sh
  name: keycloak-setup-script
- files:
  - extra_resources/config/init_banner.bash
  - extra_resources/config/metaflow_config.json
  - extra_resources/config/python_setup.py
  - extra_resources/config/opalbanner/build_log.json
  - extra_resources/config/opalbanner/package.json
  - extra_resources/config/opalbanner/static/lib_index_js.c5bdfaa1aff4b7b02e37.js
  - extra_resources/config/opalbanner/static/lib_index_js.c5bdfaa1aff4b7b02e37.js.map
  - extra_resources/config/opalbanner/static/remoteEntry.6dc8af8c155fe1a6f950.js
  - extra_resources/config/opalbanner/static/remoteEntry.6dc8af8c155fe1a6f950.js.map
  - extra_resources/config/opalbanner/static/style.js
  - extra_resources/config/opalbanner/static/style_index_js.57d21bebc1950465c344.js
  - extra_resources/config/opalbanner/static/style_index_js.57d21bebc1950465c344.js.map
  - extra_resources/config/opalbanner/static/vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_css-loader_dist_runtime_cssW-72eba1.adce3ce405139d293875.js
  - extra_resources/config/opalbanner/static/vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_css-loader_dist_runtime_cssW-72eba1.adce3ce405139d293875.js.map
  name: jupyterhub-config-dir
  options:
    disableNameSuffixHash: true
