tls:
  certificates:
    - certFile: "/etc/traefik/certs/tls.crt"
      keyFile: "/etc/traefik/certs/tls.key"
  stores:
    default:
      defaultCertificate:
        certFile:  "/etc/traefik/certs/tls.crt"
        keyFile: "/etc/traefik/certs/tls.key"
