# Static config
providers:
  docker:
    exposedByDefault: false
  file:
    filename: "/etc/traefik/traefik_dynamic.yml"

entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}

api:
  dashboard: false
  insecure: false

ping: true

accessLog:
  filepath: "/logs/traefik/traefik_access.json"
  format: json
  bufferingSize: 10

#Uncomment below for increased logging
# log:
#   level: DEBUG

