apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opal

# local + traefik + secrets
bases:
  - ../local
  - ../../components/traefik/

# patch traefik cluster ip to clusterIP: "10.96.30.9"
patches:
- traefik_patch.yaml