apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opal

bases:
  - ../../base/

generatorOptions:
  disableNameSuffixHash: true

resources:
  - kubernetes_files/ingress.yaml
  - kubernetes_files/init_singleuser_image.yaml
  - kubernetes_files/opal_argo_workflows.yaml
  - kubernetes_files/opal_metaflow_metadata.yaml
  - kubernetes_files/singleuser-service-account.yaml

configMapGenerator:
  - name: deployment-env
    envs:
      - k8.env

secretGenerator:
  - name: tls-certs
    files:
      - tls.crt
      - tls.key
    type: "kubernetes.io/tls"
  - name: minio-certs
    files:
      - tls.crt
    type: Opaque
  - name: argo-env
    envs:
      - argo.env

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ARGO_NAMESPACE
        value: opal
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: BASE_HREF
        value: /argo/
    - op: add
      path: "/spec/template/spec/containers/0/args/-"
      value:
        --secure=false
  target:
    kind: Deployment
    # namespace: opal
    name: argo-server