apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opal

bases:
  - ../../base/
  - ../../components/experimental

resources:
  - ingress.yaml
  - init_singleuser_image.yaml

configMapGenerator:
  - name: deployment-env
    envs:
      - k8.env
