name: hardening

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  scan_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.22.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov responses
      - name: Run tests
        run: |
          cd ${GITHUB_WORKSPACE}/docker-compose/configuration/tests/
          pytest --cov-report lcov:./coverage/lcov.info --cov=../generate_files
      - name: Code Coverage Summary Report
        uses: kcjpop/coverage-comments@v2.2
        with:
          working-directory: '${GITHUB_WORKSPACE}/docker-compose/configuration/tests'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: './coverage/lcov.info'